name = "juntas"
main = "index.js"
compatibility_date = "2024-04-03"

[assets]
directory = "./public"
binding = "ASSETS"

[[kv_namespaces]]
binding = "BOOKINGS_KV"
# Reemplazar con el ID devuelto al crear el namespace con:
# npx wrangler kv namespace create BOOKINGS_KV
id = "9c3618b7e50f4e128fe6c28d8f640c8b"
preview_id = "90f9eb082acd405c953158f53679a6de"
